### ISSUE TITLE
Suggestion : Perfect Money Voucher

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#124]
Hello, currently the Perfect Money gateway can be used when the user has an account on the Perfect Money website.
Also, due to the increase in Tron network fees, buying with Tether is not cost-effective.
For this reason, I suggest that you please add the Perfect Money voucher gateway as soon as possible.
Place a form to enter e-voucher and activation code and after confirming the transaction, the invoice will be automatically confirmed like other gateways.

**Comment by ca3tiel** [comment]
thanks @matador7495 
this is so good if we have Perfect Money voucher gateway Because in our country, payments must be made anonymously, and using a voucher is a more convenient method. Also, our country has blocked the Perfect Money website and user need a VPN to access it.
Adding the Perfect Money voucher gateway making the payment process easier and  solves many problems. it is very effective.
thanks a lot

**Comment by matador7495** [comment]
Yes, for all users in the world, using Voucher Perfect Money and Web Money is the best option

**Comment by shadow-vpn** [comment]
yes that is very useful for perfect money payment

**Comment by matador7495** [comment]
Did you add Perfect Money voucher payment gateway? You changed the status of these issues!
